import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { PINNED_TIMESTAMP, buildSbom, purlFor } from "../scripts/sbom.mjs";

/**
 * CycloneDX 1.5 SBOM — Phase 9K Task 4.
 *
 * Generated by `scripts/sbom.mjs` from `package-lock.json` using only `node:crypto` and `node:fs`.
 * `syft` and `cyclonedx` are absent on this device, and adding a dependency to describe our
 * dependencies would be a poor trade — the lockfile already holds everything an SBOM needs.
 *
 * The assertions that matter most are the ones about **truthfulness**, not shape:
 *
 *   - a `purl` must resolve to a real package, so scoped names are percent-encoded and the twelve
 *     first-party workspaces are never given registry purls;
 *   - the runtime component count is tied to the 9J closure walk's own output rather than a copied
 *     constant, so the two cannot drift;
 *   - no build-machine path, username, or hostname appears, because an SBOM is a published document.
 */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCRIPT = join(ROOT, "scripts/sbom.mjs");

/**
 * The scoped runtime packages, pinned by their exact expected purl.
 *
 * This is the assertion the plan singles out, and rightly: `@fastify/static` must encode as
 * `pkg:npm/%40fastify/static@…`. The `@` in the scope is percent-encoded per the purl spec while the
 * `/` separator is not, and hand-rolled generators break here more than anywhere else.
 *
 * The plan pinned six names. Measured now: **eleven**, and the list differs — `@isaacs/cliui` left the
 * tree with the `@fastify/static@10` security upgrade in 9K Task 1, and eight more `@fastify/*`
 * packages arrived with it. Recorded as measured rather than bent back to the plan text.
 */
const EXPECTED_SCOPED_PURLS = [
  "pkg:npm/%40fastify/accept-negotiator@2.1.0",
  "pkg:npm/%40fastify/ajv-compiler@4.0.6",
  "pkg:npm/%40fastify/error@4.2.0",
  "pkg:npm/%40fastify/fast-json-stringify-compiler@5.1.0",
  "pkg:npm/%40fastify/forwarded@3.0.2",
  "pkg:npm/%40fastify/merge-json-schemas@0.2.1",
  "pkg:npm/%40fastify/proxy-addr@5.1.0",
  "pkg:npm/%40fastify/send@4.1.1",
  "pkg:npm/%40fastify/static@10.1.3",
  "pkg:npm/%40lukeed/ms@2.0.2",
  "pkg:npm/%40pinojs/redact@0.4.0",
];

/** The twelve first-party workspaces, which must never carry a registry purl. */
const FIRST_PARTY = [
  "@bayz/capability",
  "@bayz/contracts",
  "@bayz/dashboard",
  "@bayz/gateway",
  "@bayz/identity",
  "@bayz/providers",
  "@bayz/proxy",
  "@bayz/router",
  "@bayz/security",
  "@bayz/server",
  "@bayz/storage",
  "@bayz/telemetry",
];

function sbom() {
  return buildSbom({ timestamp: PINNED_TIMESTAMP });
}

test("the document is CycloneDX 1.5 with the required metadata", () => {
  const doc = sbom();
  assert.equal(doc.bomFormat, "CycloneDX");
  assert.equal(doc.specVersion, "1.5");
  assert.match(doc.serialNumber, /^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  assert.equal(typeof doc.metadata.timestamp, "string");
  assert.ok(Array.isArray(doc.components), "components is not an array");
  assert.ok(doc.components.length > 200, `too few components: ${doc.components.length}`);
});

test("metadata.component describes BAYZ itself with its version and licence", () => {
  const doc = sbom();
  const component = doc.metadata.component;
  assert.equal(component.name, "bayz-router");
  assert.equal(component.type, "application");
  assert.match(component.version, /^\d+\.\d+\.\d+$/);
  assert.equal(component.licenses[0].license.id, "Apache-2.0");
});

test("every component carries type, name, version, and a purl", () => {
  for (const component of sbom().components) {
    assert.ok(component.type.length > 0, `${component.name} has no type`);
    assert.ok(component.name.length > 0, "a component has no name");
    assert.match(component.version, /^\d/, `${component.name} has no version`);
    assert.ok(component.purl.startsWith("pkg:npm/"), `${component.name} has a non-npm purl: ${component.purl}`);
  }
});

test("scoped purls percent-encode the @ and are pinned exactly", () => {
  /*
   * The single most breakable line in a hand-rolled generator. `%40` encodes the scope's `@`; the `/`
   * between scope and name stays literal; the `@` before the version stays literal.
   */
  const purls = new Set(sbom().components.map((component) => component.purl));
  for (const expected of EXPECTED_SCOPED_PURLS) {
    assert.ok(purls.has(expected), `missing or misencoded purl: ${expected}`);
  }

  // And no component may carry a raw `@` in its scope, anywhere in the document.
  for (const purl of purls) {
    assert.ok(!/^pkg:npm\/@/.test(purl), `unencoded scope in purl: ${purl}`);
  }
});

test("purlFor encodes scopes and leaves unscoped names alone", () => {
  // Unit-level, so the encoding rule is pinned independently of what happens to be in the tree.
  assert.equal(purlFor("@fastify/static", "10.1.3"), "pkg:npm/%40fastify/static@10.1.3");
  assert.equal(purlFor("fastify", "5.12.1"), "pkg:npm/fastify@5.12.1");
  assert.equal(purlFor("@scope/name", "0.0.1-beta.2"), "pkg:npm/%40scope/name@0.0.1-beta.2");
});

test("the runtime component count equals the 9J closure walk's own output", () => {
  /*
   * Tied to the script's output, not to a constant copied into this file. If the closure changes and
   * the SBOM does not, these two disagree and this fails — which is the whole point, since an SBOM
   * that under-reports what ships is worse than none.
   */
  const closureOutput = execFileSync(process.execPath, [join(ROOT, "scripts/dependency-closure.mjs")], {
    encoding: "utf8",
  });
  const reported = Number(/(\d+) external/.exec(closureOutput)?.[1]);
  assert.ok(Number.isInteger(reported) && reported > 0, `could not read the closure size: ${closureOutput}`);

  const runtime = sbom().components.filter((component) => component.scope === "required");
  assert.equal(
    runtime.length,
    reported,
    `the SBOM lists ${runtime.length} runtime components but the closure walk reports ${reported}`,
  );
});

test("runtime and dev components are distinguishable by scope", () => {
  const doc = sbom();
  const scopes = new Set(doc.components.map((component) => component.scope));
  // CycloneDX vocabulary: `required` ships, `optional` does not.
  assert.deepEqual([...scopes].sort(), ["optional", "required"]);
  assert.ok(doc.components.some((component) => component.scope === "optional"), "no dev components listed");
});

test("licence and integrity hash travel with each component", () => {
  const doc = sbom();
  const fastify = doc.components.find((component) => component.name === "fastify");
  assert.ok(fastify !== undefined, "fastify is missing from the SBOM");
  assert.equal(fastify.licenses[0].license.id, "MIT");

  const hash = fastify.hashes.find((entry) => entry.alg === "SHA-512");
  assert.ok(hash !== undefined, "fastify carries no SHA-512 hash");
  // The lockfile stores base64; CycloneDX wants hex, so a bad conversion shows up as a length error.
  assert.match(hash.content, /^[0-9a-f]{128}$/, `SHA-512 is not 128 hex chars: ${hash.content}`);

  // Every component with an integrity hash in the lockfile must carry one here.
  const withHashes = doc.components.filter((component) => component.hashes.length > 0);
  assert.ok(withHashes.length > 200, `only ${withHashes.length} components carry hashes`);
});

test("the twelve BAYZ workspaces are first-party subcomponents, never registry purls", () => {
  /*
   * A purl pointing at `pkg:npm/@bayz/storage@0.1.0` would be actively misleading: no such package
   * exists on npm, so anyone resolving the SBOM would get nothing, or worse, someone else's package
   * squatting that name.
   */
  const doc = sbom();
  const subcomponents = doc.metadata.component.components ?? [];
  assert.deepEqual(
    subcomponents.map((component) => component.name).sort(),
    [...FIRST_PARTY].sort(),
    "the first-party subcomponent list is wrong",
  );

  for (const component of subcomponents) {
    assert.ok(!component.purl?.startsWith("pkg:npm/"), `${component.name} carries a registry purl`);
    assert.equal(component.licenses[0].license.id, "Apache-2.0");
  }

  // And none of them may appear in the third-party component list either.
  for (const component of doc.components) {
    assert.ok(!component.name.startsWith("@bayz/"), `${component.name} is listed as a registry dependency`);
  }
});

test("the SBOM leaks no local path, username, or hostname", () => {
  /*
   * It is a published document. Leaking the build machine's layout is an information disclosure, and
   * the lockfile keys this is built from are full of `node_modules/...` paths, so this is a real risk
   * rather than a theoretical one.
   */
  const serialised = JSON.stringify(sbom());
  assert.ok(!serialised.includes(ROOT), "the SBOM contains the repository's absolute path");
  assert.ok(!/\/(home|Users)\//.test(serialised), "the SBOM contains a home directory path");
  assert.ok(!/\/root\//.test(serialised), "the SBOM contains /root");
  assert.ok(!serialised.includes(process.env.HOME ?? "\u0000never"), "the SBOM contains $HOME");
  for (const marker of ["localhost", "127.0.0.1", "BAYZ_", "file:///"]) {
    assert.ok(!serialised.includes(marker), `the SBOM contains ${marker}`);
  }
});

test("regenerating at a pinned timestamp is byte-identical", () => {
  /*
   * A diff must mean a real dependency change. Both the timestamp and the serial number have to be
   * derived rather than random for this to hold — a `randomUUID()` serial would make every run differ.
   */
  const first = execFileSync(process.execPath, [SCRIPT, "--stdout", "--timestamp", PINNED_TIMESTAMP], {
    encoding: "utf8",
  });
  const second = execFileSync(process.execPath, [SCRIPT, "--stdout", "--timestamp", PINNED_TIMESTAMP], {
    encoding: "utf8",
  });
  assert.equal(first, second, "two generations at a pinned timestamp differ");
  assert.equal(JSON.parse(first).metadata.timestamp, PINNED_TIMESTAMP);
});

test("the serial number is derived from content, not random", () => {
  // Two runs over the same tree must agree; a change in content must change it.
  const a = buildSbom({ timestamp: PINNED_TIMESTAMP }).serialNumber;
  const b = buildSbom({ timestamp: PINNED_TIMESTAMP }).serialNumber;
  assert.equal(a, b, "the serial number is not stable across runs");

  const different = buildSbom({ timestamp: "2020-01-01T00:00:00.000Z" }).serialNumber;
  assert.notEqual(a, different, "the serial number ignores the document's own content");
});

test("the script writes a file and exits 0", () => {
  const outDir = mkdtempSync(join(tmpdir(), "bayz-sbom-"));
  const out = join(outDir, "bayz.cdx.json");
  const stdout = execFileSync(process.execPath, [SCRIPT, "--out", out, "--timestamp", PINNED_TIMESTAMP], {
    encoding: "utf8",
  });
  assert.match(stdout, /sbom: PASS/, stdout);

  const doc = JSON.parse(readFileSync(out, "utf8"));
  assert.equal(doc.bomFormat, "CycloneDX");
  assert.equal(doc.specVersion, "1.5");
});

test("the script validates rather than only generating", () => {
  /*
   * The plan requires validation, and a generator that cannot reject its own bad output is not
   * validating. `--simulate-invalid` drops the required `specVersion`, and the script must fail.
   */
  let status = 0;
  let output = "";
  try {
    output = execFileSync(process.execPath, [SCRIPT, "--stdout", "--simulate-invalid"], { encoding: "utf8" });
  } catch (error) {
    status = error.status ?? 1;
    output = `${error.stdout ?? ""}${error.stderr ?? ""}`;
  }
  assert.equal(status, 1, `an invalid SBOM was accepted: ${output}`);
  assert.match(output, /sbom: FAIL/, output);
});
