#!/usr/bin/env node
/**
 * Release digests and signing — Phase 9K Task 5.
 *
 * **Owner decision: release signing is keyless Sigstore-style provenance through GitHub OIDC.** There
 * is no long-lived private signing key in this repository, none on this Termux host, and none will be
 * generated by this script. Hosted CI obtains a short-lived identity through OIDC once the project is
 * connected to GitHub.
 *
 * Three modes, and keeping them distinct is the point:
 *
 *   - **`digests` (default).** Always runs. Writes `SHA256SUMS` over every release file. Needs no key,
 *     no tool, and no network. Prints `UNVERIFIED: unsigned build` — an unsigned local build is normal
 *     and must never be conflated with a signed release.
 *   - **`keyless`.** The hosted release mode. Locally it cannot run: no OIDC issuer, no workflow
 *     identity, no `cosign` on this device. It reports `UNVERIFIED: keyless signing requires GitHub
 *     OIDC` and exits 0 **without writing anything**. Printing a success line here would be a lie.
 *   - **`--key <path>`.** An operator supplying their own key at release time, via `openssl`. Retained
 *     because it is the one route that works with no network and no CI. The key is never stored here.
 *
 * Two refusals are non-negotiable, because a signing key committed by accident is unrecoverable trust
 * loss — it lives in the history, every clone, and every mirror:
 *
 *   1. a key path inside the repository tree is refused outright;
 *   2. this script writes no private key material anywhere, ever.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** `sha256sum -c` compatible, so a user can verify with coreutils and no BAYZ tooling at all. */
export const DIGEST_MANIFEST = "SHA256SUMS";

/** Files that are release outputs rather than release inputs, and so are never digested. */
const EXCLUDED = new Set([DIGEST_MANIFEST, `${DIGEST_MANIFEST}.sig`, `${DIGEST_MANIFEST}.bundle`]);

/**
 * Is `keyPath` inside `root`?
 *
 * Uses `relative()` rather than `startsWith()`: a sibling directory named `<root>-sibling` starts with
 * the root string but is not inside it, and a naive prefix check would wave it through.
 */
export function keyIsInsideRepository(keyPath, root = ROOT) {
  const rel = relative(resolve(root), resolve(keyPath));
  return rel !== "" && !rel.startsWith("..") && !resolve(keyPath).startsWith("..");
}

/** Digest every non-excluded file in `dir`, sorted by name so the manifest is deterministic. */
export function computeDigests(dir) {
  const entries = [];
  for (const name of readdirSync(dir).sort()) {
    if (EXCLUDED.has(name)) continue;
    const path = join(dir, name);
    if (!statSync(path).isFile()) continue;
    entries.push({ name, digest: createHash("sha256").update(readFileSync(path)).digest("hex") });
  }
  return entries;
}

/** Render in `sha256sum` format: `<hex>␠␠<name>`. Two spaces is the binary-mode marker. */
export function renderManifest(entries) {
  return `${entries.map((entry) => `${entry.digest}  ${entry.name}`).join("\n")}\n`;
}

export function parseManifest(text) {
  const entries = [];
  for (const line of text.split("\n")) {
    if (line.trim() === "") continue;
    const match = /^([0-9a-f]{64}) {2}(.+)$/.exec(line);
    if (match === null) throw new Error(`malformed manifest line: ${line}`);
    entries.push({ digest: match[1], name: match[2] });
  }
  return entries;
}

/** Is `tool` runnable? Used to turn a missing tool into `UNVERIFIED` rather than a crash. */
function toolAvailable(tool) {
  try {
    execFileSync(tool, ["version"], { stdio: "ignore" });
    return true;
  } catch (error) {
    // A tool that exists but rejects `version` is still available; only ENOENT means absent.
    return error.code !== "ENOENT";
  }
}

function main(argv) {
  const flag = (name, fallback) => {
    const index = argv.indexOf(name);
    return index === -1 ? fallback : argv[index + 1];
  };

  const dir = resolve(flag("--dir", join(ROOT, "packaging/out")));
  const keyPath = flag("--key", undefined);
  const tool = flag("--tool", "openssl");
  const mode = flag("--mode", keyPath === undefined ? "digests" : "key");

  console.log("BAYZ release signing — Phase 9K Task 5");
  console.log(`  release directory: ${relative(ROOT, dir) || dir}`);
  console.log(`  mode: ${mode}`);
  console.log("");

  if (!existsSync(dir)) {
    console.error(`  release directory does not exist: ${dir}`);
    console.error("sign-release: FAIL");
    return 1;
  }

  /*
   * The digest manifest comes first and always. It needs no key, no tool, and no network, and it is
   * the part a user can verify with `sha256sum -c` regardless of how signing went.
   */
  const entries = computeDigests(dir);
  if (entries.length === 0) {
    console.error("  no files to digest");
    console.error("sign-release: FAIL");
    return 1;
  }
  writeFileSync(join(dir, DIGEST_MANIFEST), renderManifest(entries));
  console.log(`  ${DIGEST_MANIFEST}: ${entries.length} file(s)`);
  for (const entry of entries) console.log(`    ${entry.digest.slice(0, 16)}… ${entry.name}`);
  console.log("");

  if (mode === "keyless") {
    /*
     * The hosted release path. It genuinely cannot run here, so it says so and writes nothing. The
     * workflow in `.github/workflows/release-provenance.yml` is what performs it once a remote exists.
     */
    console.log("  keyless Sigstore-style provenance via GitHub OIDC is the release signing mode.");
    console.log("  It requires a GitHub Actions OIDC token, which does not exist on this host:");
    console.log("    - no remote is configured and no workflow has ever run");
    console.log("    - ACTIONS_ID_TOKEN_REQUEST_URL is unset");
    console.log("    - cosign is not installed on this device");
    console.log("");
    console.log("UNVERIFIED: keyless signing requires GitHub OIDC");
    console.log("sign-release: PASS (digests written, artifact is unsigned)");
    return 0;
  }

  if (keyPath === undefined) {
    console.log("UNVERIFIED: unsigned build");
    console.log("  No key supplied. This is the normal local case; the artifact is not signed.");
    console.log("  Hosted releases are signed keylessly through GitHub OIDC — see docs/release-verification.md.");
    console.log("sign-release: PASS (digests written, artifact is unsigned)");
    return 0;
  }

  // Refusal 1: a key inside the repository. Checked before the file is even read.
  if (keyIsInsideRepository(keyPath)) {
    console.error(`  the key path is inside the repository: ${keyPath}`);
    console.error("  A signing key committed by accident is unrecoverable trust loss: it is in the");
    console.error("  history, every clone, and every mirror. Move the key outside the repository.");
    console.error("sign-release: FAIL");
    return 1;
  }

  if (!existsSync(keyPath)) {
    console.error(`  key not found: ${keyPath}`);
    console.error("sign-release: FAIL");
    return 1;
  }

  if (!toolAvailable(tool)) {
    console.log(`UNVERIFIED: ${tool} not available`);
    console.log("  The digest manifest was written; the artifact is not signed.");
    console.log("sign-release: PASS (digests written, artifact is unsigned)");
    return 0;
  }

  const manifestPath = join(dir, DIGEST_MANIFEST);
  const sigPath = `${manifestPath}.sig`;
  try {
    // `execFile` with an argument array: an operator-supplied path never reaches a shell.
    execFileSync(tool, ["pkeyutl", "-sign", "-inkey", keyPath, "-rawin", "-in", manifestPath, "-out", sigPath], {
      stdio: ["ignore", "ignore", "pipe"],
    });
  } catch (error) {
    console.error(`  signing failed: ${String(error.stderr ?? error.message).slice(0, 300)}`);
    console.error("sign-release: FAIL");
    return 1;
  }

  console.log(`  signature: ${DIGEST_MANIFEST}.sig written`);
  console.log("  The private key was read, never copied. Nothing key-shaped was written to the release directory.");
  console.log("");
  console.log("sign-release: PASS (signed)");
  return 0;
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exitCode = main(process.argv.slice(2));
}
